version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    REPO_URI: 828171332440.dkr.ecr.ap-south-1.amazonaws.com/mini-project/brain-app-task
    CLUSTER_NAME: brain-tasks-app
    K8S_DIR: k8s

phases:
  pre_build:
    commands:
      - echo "=== Authenticating with AWS & EKS ==="
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME
      - echo ">>> Checking cluster access..."
      - kubectl get nodes || (echo "❌ Unable to access EKS cluster"; exit 1)

      - echo "=== Logging into Amazon ECR ==="
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Repository URI - $REPO_URI"
      - echo "Image Tag - $IMAGE_TAG"

      - echo "=== Installing yq (for YAML patching) ==="
      - curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
      - chmod +x /usr/bin/yq

  build:
    commands:
      - echo "=== Building Docker Image ==="
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest

  post_build:
    commands:
      - echo "=== Pushing Docker Images to ECR ==="
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest

      - echo "=== Updating kubeconfig Again (safety) ==="
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME

      - echo "=== Ensuring CodeBuild IAM Role is in aws-auth ==="
      - CODEBUILD_ROLE_ARN=$(aws sts get-caller-identity --query Arn --output text)
      - kubectl get configmap aws-auth -n kube-system -o yaml > /tmp/aws-auth.yaml
      - if ! grep -q "$CODEBUILD_ROLE_ARN" /tmp/aws-auth.yaml; then
          echo ">>> Patching aws-auth with CodeBuild role...";
          CURRENT_MAPROLES=$(yq '.data.mapRoles' /tmp/aws-auth.yaml);
          NEW_ENTRY="- rolearn: $CODEBUILD_ROLE_ARN\n  username: build\n  groups:\n    - system:masters";
          PATCHED_MAPROLES=$(printf "%s\n%s" "$CURRENT_MAPROLES" "$NEW_ENTRY");
          kubectl patch configmap aws-auth -n kube-system --type merge -p "{\"data\":{\"mapRoles\":\"$PATCHED_MAPROLES\"}}";
        else
          echo ">>> CodeBuild role already present in aws-auth.";
        fi

      - echo "=== Deploying to Kubernetes ==="
      - sed -i "s|REPLACE_IMAGE|$REPO_URI:$IMAGE_TAG|g" $K8S_DIR/deployment.yml
      - kubectl apply -f $K8S_DIR/deployment.yml --validate=false
      - kubectl apply -f $K8S_DIR/service.yml --validate=false
      - echo ">>> Waiting for rollout..."
      - kubectl rollout status deployment/brain-tasks-app || (echo "❌ Deployment failed"; exit 1)

      - echo ">>> Current Services"
      - kubectl get svc -o wide

artifacts:
  files:
    - k8s/*
