version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    REPO_URI: 828171332440.dkr.ecr.ap-south-1.amazonaws.com/mini-project/brain-app-task
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Who am I?"
      - aws sts get-caller-identity
      - echo "Login to ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - echo "Build image"
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - echo "Push image"
      - docker push $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Write image metadata for deploy step"
      - printf '{"ImageURI":"%s"}' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - imagedefinitions.json
    - k8s/**/*
    - scripts/**/*
