version: 0.2

phases:
  pre_build:
    commands:
      - echo Configuring kubectl...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-app-cluster
  build:
    commands:
      - echo Deploying to EKS...
      - kubectl apply -f k8s/deployment.yaml