version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    CLUSTER_NAME: brain-tasks-cluster
    REPO_URI: 828171332440.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app
    IMAGE_TAG: latest
    K8S_DIR: k8s

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - yum install -y awscli jq curl
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .

  build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Updating kubeconfig..."
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME
      - echo "Deploying to Kubernetes..."
      - sed -i "s|REPLACE_IMAGE|$REPO_URI:$IMAGE_TAG|g" $K8S_DIR/*.yml
      - kubectl apply -f $K8S_DIR/
      - echo "Waiting for rollout to finish..."
      - kubectl rollout status deployment/brain-task-app-deployment || true

artifacts:
  files:
    - k8s/*
    - buildspec.yml
