apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app
  labels:
    app: brain-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
        - name: brain-tasks-container
          image: 417836837538.dkr.ecr.ap-south-1.amazonaws.com/brain-app-task:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  selector:
    app: brain-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
